In [9]:
import pandas as pd
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, classification_report
from sklearn.model_selection import train_test_split

df = pd.read_csv("train.csv")
df.head()

,id,Driver,Compound,Race,Year,PitStop,LapNumber,Stint,TyreLife,Position,LapTime (s),LapTime_Delta,Cumulative_Degradation,RaceProgress,Position_Change,PitNextLap
0,0,D109,HARD,Canadian Grand Prix,2022,0,50,2,39.0,8,78.491,-7.564,21.019,0.714286,5.0,1.0
1,1,D086,HARD,Dutch Grand Prix,2025,1,27,2,7.0,4,75.095,-32.617,-223.207,0.346154,-3.0,0.0
2,2,ZON,HARD,Austrian Grand Prix,2022,0,59,3,22.0,13,70.945,-7.540,-100.529,0.819444,3.0,1.0
3,3,SPE,MEDIUM,Pre-Season Testing,2023,0,2,1,2.0,7,94.361,-7.324,-7.324,0.076923,0.0,0.0
4,4,D019,HARD,Azerbaijan Grand Prix,2022,1,26,3,6.0,2,107.878,8.965,-14.139,0.361111,3.0,0.0

In [13]:
# melakukan prediksi sederhana
# kelompokkan terlebih dahulu
features = ['LapNumber', 'Stint', 'TyreLife', 'Position', 'LapTime (s)', 'RaceProgress']

X = df[features]
y = df.PitStop

X.head()

   LapNumber  Stint  TyreLife  Position  LapTime (s)  RaceProgress
0         50      2      39.0         8       78.491      0.714286
1         27      2       7.0         4       75.095      0.346154
2         59      3      22.0        13       70.945      0.819444
3          2      1       2.0         7       94.361      0.076923
4         26      3       6.0         2      107.878      0.361111

In [14]:
# pisahkan menggunakan split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=1)

X_train.head()

        LapNumber  Stint  TyreLife  Position  LapTime (s)  RaceProgress
215889         28      2      10.0        12       92.878      0.538462
204847         25      1      25.0        10       91.448      0.328947
118844          6      1       7.0         2       77.664      0.083333
258088         28      2      18.0         8       95.822      0.368421
90334          38      2      21.0         7       82.534      0.493506

In [15]:
# mulai menggunakan
model_try = RandomForestClassifier()
model_try.fit(X_train, y_train)

# prediksi
prediction = model_try.predict(X_test)
print("Accuracy :", accuracy_score(y_test, prediction))
print(classification_report(y_test, prediction))

Accuracy : 0.8769071366762308
              precision    recall  f1-score   support

           0       0.91      0.96      0.93     76018
           1       0.56      0.37      0.45     11810

    accuracy                           0.88     87828
   macro avg       0.74      0.66      0.69     87828
weighted avg       0.86      0.88      0.87     87828

In [17]:
# coba dengan data test
dft = pd.read_csv("test.csv")
predict_tools = dft[features]

predict_final = model_try.predict(predict_tools)
print(predict_final)

[0 0 0 ... 0 0 0]

In [20]:
# masukkan ke submission
submission = pd.DataFrame({
    'id': dft['id'],         # Ganti dengan kolom ID yang sesuai format, misal: df_test_original.loc[X_test.index, 'id']
    'PitNextLap': predict_final    # Kolom hasil prediksi model lu (0 atau 1)
})

# 2. Export ke bentuk CSV tanpa memasukkan index dataframe pandas
submission.to_csv('submission.csv', index=False)

# 3. Intip isi file submission-nya buat mastiin format udah bener
print("File submission berhasil dibuat! Ini 5 baris pertamanya:")
print(submission.head())

File submission berhasil dibuat! Ini 5 baris pertamanya:
       id  PitNextLap
0  439140           0
1  439141           0
2  439142           0
3  439143           0
4  439144           0